---
language: minimal
services:
  - docker
env:
  - OS_VERSION=centos-7
  - OS_VERSION=centos-8
  - OS_VERSION=fedora-29
  - OS_VERSION=fedora-30
  - OS_VERSION=fedora-31
  - OS_VERSION=debian-8

before_script:
  - sudo curl -fsSL https://goss.rocks/install | sudo sh
  - sudo pip install ansible
  - ansible-playbook builds/build-playbook.yml -v

script:
    - echo "Yay testing"
    #- docker build --file builds/artifacts/${OS_VERSION}/Containerfile --tag testing-zcashd:${OS_VERSION} .
    #- GOSS_FILES_PATH=test dgoss run testing-zcashd:${OS_VERSION}
