ARG install_dir=/opt/zcashd

FROM {{ os_version }} AS builder

ARG install_dir
{% if system_dependencies|length > 0 %}

RUN {{ package_manager }} update -y && \
    {{ package_manager }} install -y {{ system_dependencies|join(' ') }}
{% endif %}

WORKDIR $install_dir
RUN git clone {{ git_url }} $install_dir && git reset --hard {{ git_version }}
RUN $install_dir/zcutil/build.sh -j$(nproc)
RUN $install_dir/zcutil/fetch-params.sh

FROM {{ os_version }}

LABEL maintainer="O1.IO"

ARG install_dir
COPY --from=builder $install_dir/src/zcashd $install_dir/src/zcash-cli /usr/bin/
COPY --from=builder /root/.zcash-params /root/.zcash-params

COPY scripts /usr/bin
RUN chmod +x /usr/bin/entrypoint.sh /usr/bin/start-zcashd.sh
COPY entrypoints  /entrypoint.d

ENTRYPOINT ["entrypoint.sh"]

CMD ["start-zcashd.sh"]
