---
- name: Playbook for building 0x01 Container file template Containerfiles
  hosts: localhost
  tasks:
    - name: Load build arguments
      include_vars: "{{ playbook_dir }}/build-args.yml"
    - name: Ensure existence of build directories
      file:
        path: "{{ playbook_dir }}/artifacts/{{ item.name }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      with_items: "{{ build_matrix }}"
    - name: Render Containerfiles (to be built) based on build-args
      template:
        src: "{{ playbook_dir }}/templates/Containerfile.j2"
        dest: "{{ playbook_dir }}/artifacts/{{ item.name }}/Containerfile"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
      vars:
        os_version: "{{ item.os_version | default(default_os_version) }}"
      with_items: "{{ build_matrix }}"
    - name: Build each OS based image from parent DIR of playbook
      become: true
      when: build_images
      command:
        chdir: "{{ playbook_dir.split('/')[0:-1]|join('/') }}"
        cmd: "docker build --file {{ playbook_dir }}/artifacts/{{ item.name }}/Containerfile --tag staged-template:{{ item.name }} ."
      with_items: "{{ build_matrix }}"
